### PR TITLE
Updated dependencies and dependabot

### PR DESCRIPTION
**Pull request by pinkforest**
* Updates tiny_http that was insecure
* Brings other dependency fixes
* Adds automatic deps push requests via dependabot.yml (enable from Insights -> dependencies)

### CODE REVIEW

**Comment by CohenArthur** [comment]
I am not familiar with dependabot. How come so many commits are present even though the only "change" is for `tiny_http`? Are the changes being made to the Cargo.lock file?

**Comment by pinkforest** [comment]
@CohenArthur @Skallwar it's because I enabled dependabot on my fork and I tested & merged all PRs dependabot did.

And yes since the project did not .gitignore cargo.lock it's also updated to pin the exact versions, 

GitHub shows files changed in very nice elegant way in both rich and raw modes.

The merged commits contain crucial information that was changed between the versions and serves as audit point.

I just like prefer merge pattern instead of squash and dependabot pushes PR per dependency for good reasons.

This was just to catchup on what dependabot found crucial to update so you don't end up with multile PRs.

**Review by Skallwar — APPROVED** [review]

**Comment by Skallwar** [comment]
Thanks a lot for taking the time

**Review by CohenArthur — APPROVED** [review]
Thanks!

**Pull request merged**
