### PR TITLE
Stops freezing Firefoxes looking into the repo

### PR DESCRIPTION
**Pull request by pinkforest**
And crate.rs page so probably best to put into release.

### CODE REVIEW

**Comment by pinkforest** [comment]
@Skallwar 
Fixes #136 

Also I took the liberty moving the logo image to media/ too

**Review by Skallwar — APPROVED** [review]

**Comment by Skallwar** [comment]
Is it possible to add a bit more height to the image? I like the 150col/20row (maybe 25) better but the height need to be bigger

**Comment by pinkforest** [comment]
Geneally it is bad idea to pick both width and height for images as it can break between viewing ports otherwise.

In general we define only width or height for image sources.

This allows either the width or height to scale appropriately according to the viewing device keeping it "portable"

If we are talking about rows/columns amount though,

Increasing rows would made it unreadable in iPad and other devices, 

I had to balance this out one to see it fits everywhere to give general idea about how the tool works as-of-now.

Bigger payoff will come from proper timings and more thoughtful CLI interactivity we can add to the binary with crossterm crate.

btw - I got them all in lined out against each other here:

https://github.com/pinkforest/svg-testing-bloat

Writing this all on 38" 3840x1660 Ultra Wide Screen :)

**Comment by pinkforest** [comment]
We have to take some columns out to make it scale right. I'll try regular expression on the front bit.

**Review by CohenArthur — APPROVED** [review]
Thanks for doing this!

**Comment by pinkforest** [comment]
Looks like it was in the recording how it determined the aspect ratio.. I didn't sleep last night so making some bad mistakes.

**Comment by pinkforest** [comment]
The CPU core util is still at 20% when firefox rolls those lines fast.

I am not sure the SVG as-is worth keeping in the repo README.md

Typically it pays attention to set proper keyframes with meaningful information.

And if you do a gif at that size given font size 14px.. yeah well good luck playing that ! :)

Can we just yank this SVG for now?

**Comment by pinkforest** [comment]
@CohenArthur 

What do you prefer:
https://github.com/pinkforest/svg-testing-bloat

Please note that it has to work in all kinds of different devices and CPU usage may be a problem.

Every time that fast scroller is running it takes about 20-30% core time... 

Not sure we want to have some CPU intensive in README.md

**Comment by pinkforest** [comment]
@ColenArthur

This is little easier on CPU, I took the minimum frame time up to 100ms

https://raw.githubusercontent.com/pinkforest/svg-testing-bloat/main/suckit-adjusted-120cols-40rows-100ms.svg

**Comment by pinkforest** [comment]
@CohenArthur @Skallwar 

And this is more close to original but still takes 30-50% CPU core rendered with 120 minimum frame time.

https://raw.githubusercontent.com/pinkforest/svg-testing-bloat/main/suckit-150cols-60rows-120ms.svg

And it gets scaled down in README.md (last entry)
https://github.com/pinkforest/svg-testing-bloat/blob/main/README.md

**Comment by Skallwar** [comment]
> If we insist on using this scroller SVG I think the 120cols 40rows with 100ms one balances the CPU use

Go for this one then

**Review by Skallwar — APPROVED** [review]

**Comment by pinkforest** [comment]
> Go for this one then

changed :tada: 

Now :zzz:

**Pull request merged**
