### PR TITLE
Lets make this non-unix specific for our windows based friends

### PR DESCRIPTION
**Pull request by mr-bo-jangles**

### CODE REVIEW

**Review by CohenArthur — APPROVED** [review]
Thanks :D

**Comment by CohenArthur** [comment]
I think a good thing to add would be CI using a Windows build. This way we could know if the changes are actually good, and if the rest of the project is okay on a different OS

**Review by Skallwar — APPROVED** [review]
LGTM. This can't be merged right now because of an issue with the new release

**Comment by mr-bo-jangles** [comment]
> 
> 
> I think a good thing to add would be CI using a Windows build. This way we could know if the changes are actually good, and if the rest of the project is okay on a different OS

The only issue I found running it on windows was that the color codes were generated, but obviously are meant for another OS. I just wanted to remove the blocker of performing symlinks

**Comment by CohenArthur** [comment]
> > I think a good thing to add would be CI using a Windows build. This way we could know if the changes are actually good, and if the rest of the project is okay on a different OS
> 
> The only issue I found running it on windows was that the color codes were generated, but obviously are meant for another OS. I just wanted to remove the blocker of performing symlinks

Ah, right. Well that's okay for now I'd say, but we should open an issue for this and use an OS agnostic coloring library or remove colors altogether on Windows. Do you want to open the issue?

**Pull request merged**
