### PR TITLE
Adds badges

### PR DESCRIPTION
**Pull request by pinkforest**
**Adds**
* Dependencies deps.rs badge
* Crates.io badge
* Docs.rs badge
* License badges

**Suggestions**
* Maybe enable & add [dependabot.yml](https://github.com/pinkforest/gis_puller/blob/main/.github/dependabot.yml) - sent a PR https://github.com/Skallwar/suckit/pull/123
* Figure out Minimum MSRV Rust and add it

**Note**
* Cache control max for badges e.g. in deps.rs is 4hours and github proxy uses that, no need to override it's a feature :)
* https://github.com/tiny-http/tiny-http/issues/173
* #123 brings tiny_http up to date

### CODE REVIEW

**Comment by CohenArthur** [comment]
Thanks a lot for the pull request and the suggestions!

**Review by CohenArthur — APPROVED** [review]

**Comment by pinkforest** [comment]
@CohenArthur @Skallwar thanks for the kind words. More to come! :)

**Review by Skallwar — APPROVED** [review]
LGTM, thanks!

**Comment by CohenArthur** [comment]
@pinkforest Once you'll have rebased feel free to ping us and we'll merge this PR. Could you also open an issue regarding the minimal Rust version needed?

**Comment by pinkforest** [comment]
@CohenArthur thanks added issue #130 and rebased

**Pull request merged**
