### PR TITLE
Filter links before downloading / adding to the queue

### PR DESCRIPTION
**Pull request by raphCode**
This commit speeds up scraping for scenarios where pages have a high branch factor, that is many links and a majority of these links is excluded by the --exclude / --include rules.
This also improves memory usage in these scenarios since the links are not stored.
Also the network traffic is reduced by not downloading these links in the first place.

### CODE REVIEW

**Review by CohenArthur — APPROVED** [review]

**Comment by raphCode** [comment]
I thought a bit more, and what we want is separate regex filters for downloading and visiting:
- specify what to download while still exploring and finding all links
- exclude any irrelevant links (speeding up crawling, better memory footprint etc)

To put in other words:
- just using the proposed `--in/exclude-download` arguments represents the traditional behavior like before the PR: visiting all pages, downloading what matches.
- using `--in/exclude-download` with `--visit-filter-is-download-filter` behaves like the initial commit in this PR: not visiting pages that won't be downloaded
- anything in between can be specified by using `--in/exclude-download` with `--in/exclude-visit`. Of course, only visited pages can be downloaded.

**Review by Skallwar — APPROVED** [review]

**Review by Skallwar — CHANGES_REQUESTED** [review]
Thanks you very much. This is good idea. Please add some tests for this and we will merge it

**Comment by raphCode** [comment]
I always fail to think of useful tests.
How would you check that some links are not visited?

I could just duplicate the existing tests in `filters.rs` and make them use the visit filters instead of the download filters, relying on the side effect that unvisited links are not downloaded as well.
But I think this does not capture the distinction that is intended with those options.

**Comment by Skallwar** [comment]
> How would you check that some links are not visited?

You could put valid link (that should be downloaded) to visit in a page that should not be visited and check if the valid link has been downloaded or not.

**Comment by raphCode** [comment]
Basically just duplicated the existing tests and adjusted for visit filter regex.

**Comment by telugu-boy** [comment]
Any update on this? It's almost a bug without the feature at this point, --exclude and --include are not doing what they are supposed to 😢

**Comment by Skallwar** [comment]
Sorry for the delay, I will review this tomorrow

**Review by CohenArthur — APPROVED** [review]
Sorry for the delay! Looks good to me!

**Review by Skallwar — APPROVED** [review]
Thanks you very much! Sorry once again for the delay

**Comment by Skallwar** [comment]
Humm the CI is not running

**Comment by Skallwar** [comment]
We are in this case... https://github.community/t/missing-approve-and-run-button/200572
I will merge this in the meantime, hopefully Github will fix this

**Comment by Skallwar** [comment]
The CI works perfectly on master, all good :rocket: :fire:

**Pull request merged**
